### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by relaxin07** [relaxin07/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by newrelax07** [comment]
0959131095
relaxin071 skype
relaxinfh07@gmail.com

**Comment by relaxin07** [comment]
дякуюююю
