### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by relaxin07** [relaxin07/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by newrelax07** [comment]
**Education** 
1997-2008  School 
2009-2014  Sumdu University

**Work experience**
2014-2016  System Administrator in Dvina
2017-2018  Html/css developer  in AppFox
2019-2021  System Administartor in Sumy Gas
