### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by relaxin07** [relaxin07/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by newrelax07** [comment]
Skills:
Html  , css , sass,  bootsrap , npm ,  Jquery ,  Javascript , React ,Redux ,

Language: 
Русский , Украінска  , English 

Hoobie 
Football , chess, computer games , runnig.
